services:
  bipkisite-backend:
    platform: linux/amd64
    build: ./backend
    image: siegfriedschmidt/bipkisite-backend
    container_name: bipkisite-backend 
    environment:
      - PORT=8001
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - COOKIE_AUTH_SECRET=changeme
      - JWT_SECRET=changeme
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    #volumes:
    #  - ./data:/app/data
    networks:
    #  - proxy-net
      - default
    restart: "no"

  bipkisite-frontend:
    platform: linux/amd64
    build: ./frontend
    image: siegfriedschmidt/bipkisite-frontend
    container_name: bipkisite-frontend
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=8000
      - BACKEND_HOSTNAME=bipkisite-backend
      - BACKEND_PORT=8001
    ports:
      - '127.0.0.1:8000:8000'
    networks:
      - default
    restart: "no"
    
#networks:
#  proxy-net:
#    external: true

