services:
  signaler:
    platform: linux/amd64
    build: .
    image: siegfriedschmidt/bipkisite-backend
    container_name: signaler
    #ports:
    #  - "127.0.0.1:8001:8001"
    environment:
      - PORT=8001
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    restart: "no"
